### ISSUE TITLE
[Improvement] Convert Zbirka to use PDFs instead of PNGs

### ISSUE THREAD

**Issue by Nomalah** [ACC-Hymns/acchymns-web#54]

**Comment by ruthrootz** [comment]
@Nomalah @Christoffyw Do you guys have an example `internal.json` file I can check out? Or just an outline of the schema? Thanks :)

**Comment by Nomalah** [comment]
@ruthrootz All of the files in PDFAnalyzer are kinda just thrown together, lol. Modify any of those files to fit the needs of your specific pdfs, I would start with the HymnsOfPraise.py, as I found it to be the most helpful when splitting the Zion's Harp Translations. I believe the format for the output, is:
{
  "title": "Title of the song"
  "page_num": "the page number that the title of the song was found on"
  "starts_at_top": "whether or not the title was found at the top of the page (you'll have to change your y value detection for this)"
}
Using this, we use PDFCropper.py to split the pdf, by using the current song's page number, and whether or not the next song starts at the top of a page, it splits the starting PDFs into PDFs for each song. From there, we manually crop each song pdf to size (if it includes another song)

Lmk if you want to know more info, I'd like to make a private repo with all the actual song files in the future but I'm a little burnt out for this 2.0 release, we're already on 2.0.2 with our hot-fixes lol.

**Comment by ruthrootz** [comment]
Sweet, thanks, that helps a ton!

**Comment by Nomalah** [comment]
Ceda has sent me the music files for Zbirka, I still only have up to #485 though... I'm putting together a private hymnal repo tonight.

**Comment by ruthrootz** [comment]
@Nomalah I have the full PDF of the newest edition, which includes the newest songs. I can upload that to the private repo as well.

**Comment by Nomalah** [comment]
@ruthrootz Bump the version number in package.json to fix the IOS workflow

**Comment by ruthrootz** [comment]
@Nomalah Gotcha, I would've forgotten to do that, thanks!
